### PR TITLE
Added Atmel target

### PR DESCRIPTION
**Pull request by Parthasarathy**

### CODE REVIEW

**Comment by 0xc0170** [comment]
Hi,

We can't merge this until Techcon as we started code freeze.
We can set up a branch in this module, which allows to at least use this module locally using yotta link. 
Same applies to mbed-hal.

Thanks for understanding.

**Comment by Parthasarathy** [comment]
Thanks for the update Martin,
Can you please setup a branch for cmsis and mbed-hal we will make use of it for the demo.

**Comment by 0xc0170** [comment]
Done, branches dev_atmel created on both repositories. Please send PR to those branches.

**Comment by Parthasarathy** [comment]
Thanks Martin

**Comment by 0xc0170** [comment]
I am closing this one, as you can't change the destination branch within a pull request.

**Pull request closed without merging**
