### PR TITLE
Update cmsis_nvic.c

### PR DESCRIPTION
**Pull request by mlnx**

### CODE REVIEW

**Comment by autopulated** [comment]
Was there an offline review for this?

@bogdanm @0xc0170

**Comment by mlnx** [comment]
Yes, there was an review with @0xc0170 
This will remain in the dev_nxp branch for now

**Comment by 0xc0170** [comment]
I had on my mind generic change just compare VTOR < NVIC RAM address :-)
We are talking to NXP to get more details about their setup because I suspect this does not completely fixes the problem.

**Comment by autopulated** [comment]
OK, btw this introduced mixed tabs and spaces ;)

**Pull request merged**
