### PR TITLE
add targetDependency on cmsis-core-nxp

### PR DESCRIPTION
**Pull request by scottt**
I've added CMSIS-CORE support for the NXP LPC1114 in cmsis-core-lpc111x
and this patch enables it in cmsis-core.

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can you please sign http://developer.mbed.org/contributor_agreement/ ?

**Comment by scottt** [comment]
I just did.

**Comment by scottt** [comment]
@0xc0170, is there anything more I can do to facilitate the merging of this patch or are we waiting on some paperwork?

**Comment by 0xc0170** [comment]
This needs to be postponed, mainly because of the feature freeze. We will get back to you with more details. Thanks for understanding

**Comment by 0xc0170** [comment]
An update, there's dev_nxp branch here for nxp development. The modules are not yet public, can't provide an estimate at the moment.

I am closing this. Thanks for understanding

**Pull request closed without merging**
